products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('products/', views.products, name='products_front'),
]

users/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('signup/', views.register_user, name='signup'),    
]

web/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.front, name='front'),
    path('home/', views.home, name='home'),
    path('products/', include('products.urls')),
    path('about/', views.about, name='about'),
    path('register/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50) 
    discription = models.TextField()
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    img2 = models.ImageField(default='fallback.png', blank=True)
    img2 = models.ImageField(default='fallback.png', blank=True)
    price = models.CharField(max_length=50, default='__')


    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

products/views.py
from django.shortcuts import render
from .models import Post


# Create your views here.


def products(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'products/products.html', {'posts':posts})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils import timezone
from django.urls import reverse
from .models import *

def login_user(request):
    user_aut = False
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate (request=request, username = username, password=password)
        if user is not None:
            login(request, user)
            user_aut = True
            return redirect('home')
        else:
            messages.error(request, '*Invalid username or password')
            return redirect('users:login')
    return render(request, 'users/login.html')
def register_user(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        user_data_has_error = False

        if User.objects.filter(username=username).exists():
            user_data_has_error = True
            messages.error (request, "*Username already exists")
        if User.objects.filter(email=email).exists():
            user_data_has_error = True
            messages.error (request, "*Email already exists")
        if len(password) < 5 :
            user_data_has_error = True
            messages.error (request, "*Password must be atleast 5 characters")
        if not user_data_has_error :
            new_user = User.objects.create_user(
                first_name = first_name,
                last_name = last_name,
                username = username,
                email = email,
                password = password,
            )
            messages.success (request, "Account have successfully created")
            return redirect('users:login')
        else:
            return redirect('users:signup')

    return render(request, 'users/signin.html')

web/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def front(request):
    return render(request, 'front.html')
def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'about.html')

products/templates/products/products.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}products{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/products.css'%}">
{%endblock%}
{%block cart%}
    {%if user_aut == True %}
        <li class="navbar__item"><a href="/login" ><i class="fa-solid fa-cart-shopping"></i></a></li>
    {%else%}
    <li class="navbar__item" id="log_button"><a href="{% url 'users:login'%}">Login</a></li>
    {%endif%}
{%endblock%}
<div class="products__content">
{%block content%}
<h1>Featured products</h1>
<div class="items">
{% for post in posts%}
    <div class="posts">
        <div class="item__content">
        <img src="{{post.banner.url}}" height="400">
        <p class="disc">{{post.discription}}</p>
        <p class="price">{{post.price}}</p>
        <div class="buttons"><button><a href="">Add to cart <i class="fa-solid fa-cart-shopping"></i></a></button><button><a href="">Buy now</a></button></div>
        </div>
    </div>
{%  endfor %}
</div>
{% endblock%}
</div>

templates/about.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}about{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/about.css'%}">
{%endblock%}
{%block cart%}
    {%if user_aut == False %}
        <li class="navbar__item"><a href="/login" ><i class="fa-solid fa-cart-shopping"></i></a></li>
    {%else%}
    <li class="navbar__item" id="log_button"><a href="{% url 'users:login'%}">Login</a></li>
    {%endif%}
{%endblock%}
{%block content%}
    <h1>We are <span>E-Low</span></h1>
    <h3>where fashion meets confidence.</h3>
    <p id="text">Founded with the vision to offer high-quality,
        trend-forward pieces at accessible prices, E-low brings together a wide selection of urban,
        chic, and modern styles for those who dare to stand out. From everyday essentials to standout statement pieces,
        our collections are designed to inspire confidence in every step.
        Whether you're refreshing your wardrobe, dressing for an occasion, or just discovering your next favorite outfit 
        — we’re here to make your shopping experience smooth, fun, and inspiring.
        </p>
    <button id='button'>Know more</button>
        <div class="media">
            <h1>Find us here</h1>
            <h3>We can help you 24/7</h3>
            <div class="icons">
                <a href=""><i class="fa-brands fa-telegram"></i></a> 
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                <a href=""><i class="fa-brands fa-youtube"></i></a>
                <a href=""><i class="fa-brands fa-facebook"></i></a>
            </div>
        </div>
{% endblock%}
{%block js%}
<script src="{% static 'js/about.js'%}"></script>
{% endblock %}

templates/front.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    <link rel="stylesheet" href="{% static 'css/home.css'%}">

    {%block css%}
    {%endblock%}
</head>
<body>
    <!--navbar-->
    <nav class="navbar">
        <div class="navbar__elements">
            <div class="logo"><a href="{% url 'home'%}" class="navbar__logo">E-Low</a></div>
            <div class="navbar__toggel">
                <div class="navbar__toggel--line"></div>
                <div class="navbar__toggel--line"></div>
                <div class="navbar__toggel--line"></div>
            </div>
        </div>
        <div class="navbar__menu">
            <ul class="navbar__list">
                <li class="navbar__item"><a href="/" >Home</a></li>
                <li class="navbar__item"><a href="{% url 'products:products_front'%}" >Products</a></li>
                <li class="navbar__item"><a href="{% url 'about'%}" >About</a></li>
                <li class="navbar__item" id="log_button"><a href="{% url 'users:login'%}">Login</a></li>
            </ul>   
        </div>
</nav>
<!--end of navbar-->
<div class="contents">
    <div class="hero__content">
        <h5>Trade-with-70%-off</h5>
        <h1>Welcome to <span>E-low</span></h1>
        <h3>Get your fashion here</h3>
        <button class='button_one'><a href="{% url 'users:login'%}">Get started</a></button>
        <button class='button_two'><a href="{% url 'about'%}">About us</a></button>
    </div>
</div>
{% block js%}
{% endblock%}
<script src="https://kit.fontawesome.com/b50902bacd.js" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}home{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
{%endblock%}
{%block cart%}
    {%if user_aut == false %}
        <li class="navbar__item"><a href="/login" ><i class="fa-solid fa-cart-shopping"></i></a></li>
    {%else%}
    <li class="navbar__item" id="log_button"><a href="{% url 'users:login'%}">Login</a></li>
    {%endif%}
{%endblock%}
{%block content%}
<div class="hero__content">
    <h5>Trade-with-70%-off</h5>
    <h1>Welcome to <span>E-low</span></h1>
    <h3>Get your fashion here</h3>
    <button class='button_one'><a href="{% url 'users:login'%}">Get started</a></button>
    <button class='button_two'><a href="{% url 'about'%}">About us</a></button>
</div>
{% endblock%}

templates/layout.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title%}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    {%block css%}
    {%endblock%}
</head>
<body>
    <!--navbar-->
    <nav class="navbar">
        <div class="navbar__elements">
            <div class="logo"><a href="{% url 'home'%}" class="navbar__logo">E-Low</a></div>
            <div class="navbar__toggel">
                <div class="navbar__toggel--line"></div>
                <div class="navbar__toggel--line"></div>
                <div class="navbar__toggel--line"></div>
            </div>
        </div>
        <div class="navbar__menu">
            <ul class="navbar__list">
                <li class="navbar__item"><a href="{% url 'home'%}" >Home</a></li>
                <li class="navbar__item"><a href="{% url 'products:products_front'%}" >Products</a></li>
                <li class="navbar__item"><a href="{% url 'about'%}" >About</a></li>
                <li class="navbar__item"><a href="/contact" >Profile</a></li>
                {% block cart%}
                <li class="navbar__item"><a href="/login" ><i class="fa-solid fa-cart-shopping"></i></a></li>
                {% endblock%}
            </ul>   
        </div>
</nav>
<!--end of navbar-->
<div class="contents">
    {% block content%}
    

    {% endblock %}
</div>
{% block js%}
{% endblock%}
<script src="https://kit.fontawesome.com/b50902bacd.js" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}login__Page{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/users.css'%}">
{%endblock%}
{%block content%}
<form method="POST">

    {% csrf_token %}
<div class="form_items">
    <h1>Login</h1>
    {%if messages%}
            {% for message in messages%}
                {% if message.tags == 'error' %}
                    <h4 class="error">{{message}}</h4>
                {% else%}
                    <h4 class="success">{{message}}</h4>
                {%endif%}
            {% endfor%}
        {% endif%}
  <div class="txt_field">
    <label>Username</label>
    <input type="text" required name="username">
  </div>
  <div class="txt_field">
    <label>Password</label>
    <input type="password" required name="password" >
  </div>  
  <input type="submit" value="Login" class="submit">

  <div class="signup_link">
    <a href="">Forgot password?</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Have no account? <a href="{% url 'users:signup'%}">Signup</a>
    
    
  </div>
</div>
</form>
{% endblock%}

users/templates/users/register.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}account__page{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/login.css'%}">
{%endblock%}
{%block content%}

{% endblock%}

users/templates/users/signin.html
{% extends 'layout.html'%}
{% load static%}
{% block title%}signup__page{%endblock%}
{%block css%}
    <link rel="stylesheet" href="{% static 'css/users.css'%}">
{%endblock%}
{%block content%}
    <form method="POST">

        {% csrf_token %}
      
      <div class="form_items">
      <h1>Signup here</h1>
        {%if messages%}
            {% for message in messages%}
                {% if message.tags == 'error' %}
                    <h4 class="error">{{message}}</h4>
                {% else%}
                    <h4 class="success">{{message}}</h4>
                {%endif%}
            {% endfor%}
        {% endif%}
        <div class="txt_field">
          <label>First Name</label>
          <input type="text" required name="first_name" >
        </div>
    
        <div class="txt_field">
          <label>Last Name</label>
          <input type="text" required name="last_name" >
        </div>
    
        <div class="txt_field">
          <label>Username</label>
          <input type="text" required name="username">
        </div>
    
        <div class="txt_field">
          <label>Email address</label>
          <input type="email" required name="email">
        </div>
    
        <div class="txt_field">
          <label>Password</label>
          <input type="password" required name="password" >
        </div>    
    
        <!-- <div class="pass">Forgot Password?</div> -->
        <input type="submit" value="Register" class="submit">
        <div class="signup_link">
          Already have an account? <a href="{% url 'users:login' %}">Login</a>
        </div>
      </div>
      </form>

{% endblock%}
    